project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "Syllabus.md"
    - "*.ipynb"
    - "!nbs/**"
    - "!installation/**"
    - "!example_course/**"
    - "!LLMs-from-scratch/**"
    - "!COURSE_*.md"
    - "!*_PLAN.md"

website:
  navbar:
    title: "GEOG<br>288KC"
    right:
      - text: 🏠 home
        href: index.qmd
      - text: 📋 syllabus
        href: Syllabus.html
      - text: 🗓️ weekly materials
        menu: 
          - text: "🏗️ Stage 1: Foundation Building"
          - text: 1️⃣ Week 1 - Geospatial Data Foundations
            href: course-materials/week1.qmd
          - text: 2️⃣ Week 2 - Spatial-Temporal Attention Mechanisms
            href: course-materials/week2.qmd
          - text: 3️⃣ Week 3 - Complete GFM Architecture
            href: course-materials/week3.qmd
          - text: "🚀 Stage 2: System Training"
          - text: 4️⃣ Week 4 - Pretraining Implementation
            href: course-materials/week4.qmd
          - text: 5️⃣ Week 5 - Training Loop Optimization
            href: course-materials/week5.qmd
          - text: 6️⃣ Week 6 - Model Evaluation & Analysis
            href: course-materials/week6.qmd
          - text: 7️⃣ Week 7 - Integration with Existing Models
            href: course-materials/week7.qmd
          - text: "🎯 Stage 3: Real-World Application"
          - text: 8️⃣ Week 8 - Task-Specific Fine-tuning
            href: course-materials/week8.qmd
          - text: 9️⃣ Week 9 - Model Implementation & Deployment
            href: course-materials/week9.qmd
          - text: 🎯 Week 10 - Project Presentations & Synthesis
            href: course-materials/week10.qmd
      - text: 💻 interactive sessions
        menu:
          - text: "🏗️ Stage 1: Foundation Building"
          - text: Session 1 - 📊 Geospatial Data Foundations
            href: course-materials/interactive-sessions/session1_data_foundations.qmd
          - text: Session 2 - 🧠 Spatial-Temporal Attention Mechanisms
            href: course-materials/interactive-sessions/session2_attention_mechanisms.qmd
          - text: Session 3 - 🏗️ Complete GFM Architecture
            href: course-materials/interactive-sessions/session3_architecture.qmd
          - text: "🚀 Stage 2: System Training"
          - text: Session 4 - 🔥 Pretraining Implementation
            href: course-materials/interactive-sessions/session4_pretraining.qmd
          - text: Session 5 - ⚙️ Training Loop Optimization
            href: course-materials/interactive-sessions/session5_training_loop.qmd
          - text: Session 6 - 📈 Model Evaluation & Analysis
            href: course-materials/interactive-sessions/session6_evaluation.qmd
          - text: Session 7 - 🤝 Integration with Existing Models
            href: course-materials/interactive-sessions/session7_pretrained_integration.qmd
          - text: "🎯 Stage 3: Real-World Application"
          - text: Session 8 - 🔧 Task-Specific Fine-tuning
            href: course-materials/interactive-sessions/session8_finetuning.qmd
          - text: Session 9 - ☁️ Model Implementation & Deployment
            href: course-materials/interactive-sessions/session9_deployment.qmd
          - text: Session 10 - 🎯 Project Presentations & Synthesis
            href: course-materials/interactive-sessions/session10_presentations.qmd
      - text: 🎓 lectures
        menu:
          - text: Lecture 1 - 🧠 Foundation Model Architectures
            href: course-materials/lectures/lecture1_architectures.qmd
          - text: Lecture 2 - 🌍 Geospatial Data & Remote Sensing
            href: course-materials/lectures/lecture2_geospatial_data.qmd
          - text: Lecture 3 - 🔧 Fine-tuning Strategies
            href: course-materials/lectures/lecture3_finetuning.qmd
          - text: Lecture 4 - 📐 Multi-modal Learning
            href: course-materials/lectures/lecture4_multimodal.qmd
          - text: Lecture 5 - 🔍 Model Evaluation & Validation
            href: course-materials/lectures/lecture5_evaluation.qmd
          - text: Lecture 6 - ☁️ Cloud & Scalable Computing
            href: course-materials/lectures/lecture6_cloud_computing.qmd
      - text: 📁 projects
        menu:
          - text: 📝 Project Application Template
            href: course-materials/projects/project-application-template.qmd
          - text: 📋 Project Proposal Template
            href: course-materials/projects/project-proposal-template.qmd
          - text: 🚀 MVP Presentation Template
            href: course-materials/projects/mvp-template.qmd
      - text: 👀 cheatsheets
        href: cheatsheets.qmd
      - text: 📚 resources
        menu:
          - text: 🌍 Earth Engine Documentation
            href: https://developers.google.com/earth-engine
            target: _blank
          - text: 🔥 PyTorch Documentation
            href: https://pytorch.org/docs/
            target: _blank
          - text: 🗺️ TorchGeo Documentation
            href: https://torchgeo.readthedocs.io/
            target: _blank
          - text: 🤗 HuggingFace Documentation
            href: https://huggingface.co/docs
            target: _blank
          - text: 🌐 Prithvi Foundation Model
            href: https://github.com/NASA-IMPACT/Prithvi-100M
            target: _blank
          - text: 🛰️ SatMAE Model
            href: https://github.com/microsoft/SatMAE
            target: _blank
          - text: 🧠 UCSB AI Sandbox
            href: https://ai-sandbox.ucsb.edu
            target: _blank
          - text: 📊 MLflow Documentation
            href: https://mlflow.org/docs/
            target: _blank
          - text: ⚡ FastAPI Documentation
            href: https://fastapi.tiangolo.com/
            target: _blank
          - text: 📈 Weights & Biases
            href: https://docs.wandb.ai/
            target: _blank
      - icon: github
        href: https://github.com/kellycaylor/geoAI
        target: _blank
  page-footer:
    background: dark
    right: This website is built with [{{< fa brands github title="the github octocat logo" >}}](https://github.com/environmental-data-science/geog-288kc-geospatial-foundation-models) and [Quarto](https://quarto.org/)
    left: |
      <img src="/images/geog-logo.png" alt="The Department of Geography logo" width="250"/>
format:
  html:
    theme: meds-website-styles.scss
    toc: true
    title-block-banner: true
    page-layout: full
    code-fold: true
    code-tools: true
    jupyter: geoai

filters:
  - fontawesome

execute:
  freeze: auto

editor: source