name: geoAI
channels:
  - conda-forge
  - pytorch
dependencies:
  # Python version
  - python=3.11

  # Core scientific computing with Mac optimizations
  - numpy=1.26.4  # Pinned to 1.x for PyTorch compatibility
  - pandas>=2.3
  - scipy>=1.15
  - matplotlib>=3.10
  - seaborn>=0.13

  # PyTorch with Metal Performance Shaders (MPS) for Apple Silicon
  - pytorch>=2.2
  - torchvision>=0.17
  - torchaudio>=2.2
  # Note: These versions include MPS support for Apple Silicon GPU acceleration

  # Intel MKL optimizations for Mac
  - mkl>=2023.2
  - blas=*=mkl

  # Machine learning core
  - scikit-learn>=1.7
  - joblib>=1.5
  - threadpoolctl>=3.6

  # HuggingFace ecosystem
  - transformers>=4.55
  - datasets>=3.6
  - huggingface_hub>=0.34
  - accelerate>=1.9
  - tokenizers>=0.21
  - safetensors>=0.5

  # Geospatial libraries
  - gdal>=3.10
  - rasterio>=1.4
  - fiona>=1.10
  - geopandas>=1.1
  - shapely>=2.1
  - pyproj>=3.7
  - xarray>=2025.7
  - folium>=0.20

  # Earth observation
  - earthengine-api>=1.6
  - torchgeo>=0.7

  # Deep learning utilities
  - pytorch-lightning>=2.5
  - lightning>=2.5
  - timm>=1.0
  - kornia>=0.8
  - einops>=0.8

  # Computer vision
  - pillow>=11.3

  # Jupyter stack
  - jupyter>=1.1
  - jupyterlab>=4.4
  - ipykernel>=6.30
  - notebook>=7.4
  - nbformat>=5.10
  - nbclient>=0.10

  # Data processing
  - tqdm>=4.67
  - pyyaml>=6.0
  - fsspec>=2025.3
  - requests>=2.32
  - aiohttp>=3.12

  # Utilities
  - click>=8.2
  - packaging>=25.0
  - typing_extensions>=4.14

  # Additional packages via pip (not available in conda-forge or need specific versions)
  - pip>=24.0
  - pip:
    # Specialized ML libraries
    - segmentation-models-pytorch>=0.5.0
    - efficientnet-pytorch>=0.7.1
    - lightly>=1.15.22
    - pretrainedmodels>=0.7.4
    - torchmetrics>=1.8.0

    # Geospatial utilities
    - pyogrio>=0.11.0
    - mapclassify>=2.10.0
    - rtree>=1.4.0

    # Configuration management
    - hydra-core>=1.3.2
    - omegaconf>=2.3.0

    # OpenCV (pip version often works better on Mac)
    - opencv-python>=4.8.0

    # Development tools
    - black>=23.7.0
    - flake8>=6.0.0